name: Java Maven Build & Packer Validation

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  # Step 1: Java Maven Build
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-jar
          path: target/webapp-0.0.1-SNAPSHOT.jar

  # Step 2: Packer Template Validation
  packer_validate:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Packer format check
        run: packer fmt -check -diff packer/packer.pkr.hcl

      - name: Packer validate template
        run: packer validate -var-file=packer/variables.pkr.hcl packer/packer.pkr.hcl
